---
title: "T06. Genética de poblaciones"
output: pdf_document
date: "`r Sys.Date()`"
bibliography: ../references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## La pregunta de Yule

El 28 de febrero de 1908, el estadístico G. Udny Yule, discípulo de Pearson y miembro
de la escuela biométrica (crítica con el Mendelismo), dirigió un comentario a Reginald C.
Punnett, quien acababa de presentar su trabajo "Mendelismo en relación a la enfermedad"
a la *Royal Society of Medicine*, en Londres: "El autor ha dicho que la braquidactilia
es dominante. Con el paso del tiempo, uno esperaría entonces que, en la ausencia
de factores que lo contraresten, encontráramos tres personas con braquidactilia 
por cada persona normal, pero esto no es así" [@Punnett1908]. Punnet había mostrado
varios ejemplos de caracteres en plantas, animales y humanos con patrones de herencia
Mendeliana, pero se encontraba en su audiencia con una razonable resistencia a
aceptar los principios de Mendel como un fundamento general de la herencia de
cualquier carácter. Al fin y al cabo, sólo se observaban proporciones Mendelianas
en algunos casos de hibridación. Además, la pregunta de Yule revelaba una laguna
importante en el conocimiento, no solo por parte de Yule, sino también por parte
del mismo Punnett: ¿qué implicaciones tienen los principios de la herencia
Mendeliana para la composición genética de una población? El concepto de
*dominancia*, por ejemplo, parecía sugerir que con el tiempo el carácter dominante
debía establecerse como mayoritario. Tal vez el hecho de que muchos caracteres
recesivos sean extremadamente raros contribuyera a este mito.

Lo cierto es que @Yule1902 se había interesado anteriormente por comprender
las implicaciones de la herencia Mendeliana para una población con apareamiento
aleatorio y sabía perfectamente que si se fundaba una población con el 50% de
indivíduos dominantes *puros*, **AA**, y el 50% recesivos, **aa**, en las generaciones
posteriores a la segunda habría siempre un 25% de dominantes *puros* **AA**,
un 50% de dominantes *híbridos* (heterocigotos, **Aa**), y un 25% de recesivos **aa**.
Tal vez el hecho de haber manejado ejemplos con sólo estas frecuencias genotípicas
motivaron su interpretación errónea de la braquidactilia.

El caso es que, Punnett no respondió exactamente a lo que se le planteaba y a su
regreso a Cambridge consultó a uno de los matemáticos más brillantes de la época:
Godfrey Harold Hardy. La cuestión era cómo iban a cambiar las frecuencias de los
tres genotipos posibles de un carácter Mendeliano en una población con reproducción
aleatoria.

## La solución de G.H. Hardy

@Hardy1908 no tardó en demostrar que los principios de la herencia Mendeliana no
daban ningún motivo para pensar que un carácter dominante debiera aumentar su
frecuencia, ni que uno recesivo debiera disminuirla con el tiempo. Su razonamiento
fue el siguiente. Supongamos que en la población existen los genotipos **AA**,
**Aa** y **aa** en proporciones $P$, $H$ y $Q$. De acuerdo con la herencia
Mendeliana los heterocigotos producen la mitad de sus gametos de cada tipo, de
manera que la reproducción aleatoria, que consistiría en reunir dos gametos al
azar, produciría la combinación **AA** con frecuencia $P'=\left(P+\frac{H}{2}\right)^2$,
la combinación **Aa** con frecuencia
$H'=2\left(P+\frac{H}{2}\right)\left(Q+\frac{H}{2}\right)$, y la combinación **aa**
con frecuencia $Q'=\left(Q+\frac{H}{2}\right)^2$. Siendo esto así, la única manera
de que la distribución de genotipos se mantenga constante és que $P'=P$, $H'=H$ y
$Q'=Q$. Cualquiera de estas ecuaciones, junto con la condición de que $P+H+Q=1$,
nos conducen a la expresión de la condición necesaria y suficiente para que las
frecuencias genotípicas no cambien con el tiempo: $H^2 = 4PQ$.

Esta relación entre las frecuencias genotípicas, $H^2=4PQ$, no es necesaria en la
primera generación. Sin embargo, es evidente que después de una única generación
de reproducción aleatoria, cuando la distribución de genotipos es
$P':H':Q' = \left(P+\frac{H}{2}\right)^2:2\left(P+\frac{H}{2}\right)\left(Q+\frac{H}{2}\right):\left(Q + \frac{H}{Q}\right)^2$, entonces sí se cumple que $H'^2 = 4P'Q'$.
Por lo tanto, a partir de ese momento, la distribución de genotipos sería *estable*,
es decir no cambiaría con el tiempo, excepto por las desviaciones propias de una
distribución multinomial, que son pequeñas en poblaciones suficientemente grandes.

## El equilibrio de Hardy-Weinberg y frecuencias alélicas
Puede llamar la atención que la *ley* de Hardy-Weinberg se enunciara originalmente
sin hacer ninguna referencia a la regla del cuadrado del binomio,
$(p + q)^2 = p^2 + 2pq + q^2$, donde $p$ y $q$ son las **frecuencias alélicas**
de **A** y **a**, respectivamente.
Con el tiempo, el concepto de frecuencia alélica cobró importancia, y actualmente
parece necesariamente vinculado al equilibrio de Hardy-Weinberg. Sin duda, expresar
las frecuencias genotípicas del equilibrio en función de las frecuencias alélicas
añade claridad al asunto y ayuda a transmitir la idea de que lo realmente importante,
lo que subyace a la constancia de la distribución de genotipos, es la constancia de
las frecuencias alélicas.

$$P' = p^2;\qquad H' = 2pq;\qquad Q' = q^2$$

Al fin y al cabo, el hecho de que durante cada generación los alelos que van a
ser transmitidos a la siguiente sean *conservados* por parejas, aleatorias o no,
en organismos diploides, es circunstancial: las *parejas* de alelos se destruyen
en cada ciclo de reproducción para formar otras nuevas. 

## References
